name: WDIO regression test for the task

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    wdio-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
            
            - name: Run tests desktop
              run: npm run wdio
            
            - name: Run tests mobile
              run: npm run testsMobileBrowser
